### ISSUE TITLE
Incorrect TWAP Update in swap Function of LBPair.sol

### ISSUE THREAD

**Issue by mshakeg** [traderjoe-xyz/joe-v2#114]
## Description:

There is a potential bug in the `swap` function of the `LBPair.sol` contract, specifically related to the update of the TWAP (Time-Weighted Average Price) oracle. The issue arises from passing the active bin ID after the swap logic, which may lead to incorrect TWAP calculations if bins have been crossed during the swap.

**Function Affected:**

`function swap(bool swapForY, address to) external override returns (bytes32 amountsOut)`

**Location in Code:**

https://github.com/traderjoe-xyz/joe-v2/blob/7970ebd87d3b749f9c853bc5f45850856aeb5253/src/LBPair.sol#L567

**Problem:**

The function contains the following line towards the end, after the core swap logic is executed:

```solidity
parameters = _oracle.update(parameters, activeId);
```

This line requests an update to the TWAP oracle with the current `activeId`. However, if the swap operation crosses liquidity book bins, the `activeId` will reflect the bin ID after the swap, not before. This leads to incorrect cumulative bin ID calculations and inaccurate TWAP values over a period.

**Example to Illustrate the Issue:**

1. At time `t`, the cumulative bin ID is `X` and the active bin ID is `A`.
2. At time `t+n`, a swap occurs resulting in the active bin ID changing from `A` to `A+a`

The new cumulative bin ID at `t+n` should be:
`X + n * A`

However, with the current logic, it would be:
`X + n * (A + a)`

This misrepresentation affects the average bin over the period `[t, t+n]`, leading to:
```
((X + n * (A + a)) - X) / ((t + n) - t) = A + a
```

Instead of the correct:
```
((X + n * A) - X) / ((t + n) - t) = A
```

**Proposed Solution:**

Store the active bin ID before the swap logic is executed and use this stored value to update the TWAP oracle after the swap is complete. This ensures the TWAP calculations reflect the accurate average bin ID over the period.

**Code Suggestion:**

```solidity
uint24 startBinId = activeId;
// [Execute swap logic]
// ...
parameters = _oracle.update(parameters, startBinId);
```

**Impact:**

This bug could lead to inaccurate TWAP calculations.

**Comment by mshakeg** [comment]
Hi @0x0Louis just wanted to tag you in this issue, in case you missed it

**Comment by 0x0Louis** [comment]
Hey @mshakeg, thanks for reporting this issue and the very well documented report.

However, the `activeId` mentioned at L567 is only used for the calculation of the number of crossed bins
https://github.com/traderjoe-xyz/joe-v2/blob/7970ebd87d3b749f9c853bc5f45850856aeb5253/src/libraries/OracleHelper.sol#L215

For the TWAP, it is using the `parameters.activeId`
https://github.com/traderjoe-xyz/joe-v2/blob/7970ebd87d3b749f9c853bc5f45850856aeb5253/src/libraries/OracleHelper.sol#L213

We don't need to cache the startBinId, because `parameters.activeId` is not updated yet, so it is the `startBinId`.
It is then updated just after having updated the oracle
https://github.com/traderjoe-xyz/joe-v2/blob/7970ebd87d3b749f9c853bc5f45850856aeb5253/src/LBPair.sol#L568

**Comment by mshakeg** [comment]
Hey @0x0Louis thanks for the reply so my local repo wasn't synced to `main@latest` but only up to commit https://github.com/traderjoe-xyz/joe-v2/commit/31e31f65c6e6e183d42dec8029aca5443fa2a2c3 (from 19 Dec 2023) which has the bug described here, I just pulled `latest` and I can see that you've addressed this issue just over a month ago in https://github.com/traderjoe-xyz/joe-v2/commit/265a64ebbb7c8b947ab60d2cb0f6f7ed8788f611

https://github.com/traderjoe-xyz/joe-v2/blob/31e31f65c6e6e183d42dec8029aca5443fa2a2c3/src/libraries/OracleHelper.sol#L213
